version: '3.2'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=kinesis,s3,sqs,sns
      - USE_SSL=1
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=def
    ports:
      - "4566:4566"
    volumes:
      - ./src/test/scripts:/docker-entrypoint-initaws.d
